"""
Django settings for DigitalWorkmate project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from corsheaders.defaults import default_headers, default_methods
from pathlib import Path
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent.parent
# PROFILE_DIR = "/data/web_app/backend/invoiceapp/static/eips_data/user_profile"

FRONTEND_BASE_DIR = "/data/digital_workmate_agentic/web_app_latest/backend_web/invoiceapp"

FILES_DIR = "invoiceapp/static/eips_data/invoice_data/"
# SCAN_FILES_DIR = FRONTEND_BASE_DIR + "/static/eips_data/scan_invoice_data/" 
# CLASSIFIRE_FILES_DIR = FRONTEND_BASE_DIR + "/static/eips_data/training_data/"
# ORGANIZATION_LOGO_ROOT = FRONTEND_BASE_DIR + "/static/eips_data/organization_logo/"
 
PROFILE_DIR = "invoiceapp/static/eips_data/user_profile/"
# LOG_ROOT = FRONTEND_BASE_DIR + "/static/eips_data/log/"
# MAX_FILE_COUNT = "2000"
INVOICE_DATA_ROOT = FRONTEND_BASE_DIR + "/static/eips_data/invoice_data/"
# PROFILE_ROOT = FRONTEND_BASE_DIR + "/static/eips_data/user_profile/" 
ACTIVE_LEARNING_ROOT = FRONTEND_BASE_DIR + "/static/eips_data/user_active_learning_data/"
EXCEL_EXPORT_ROOT = FRONTEND_BASE_DIR + "/static/eips_data/excel/"
# LOG_ROOT_PATH = FRONTEND_BASE_DIR + "/static/eips_data/log/"
# TRANSLATE_FILES_DIR = FRONTEND_BASE_DIR + "/static/eips_data/original_language/"


# Local API setting
API_LINK = "http://10.89.148.84:5004/digital_workmate_v1.1/invoice_app"
META_PROMPT_API_LINK = "http://10.89.148.84:5004/meta_prompt"

# Web Api Link
WEB_API_LINK='https://10.89.148.84:5002'

API_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMjI3MjQ0MSwianRpIjoiMzExMzNiNDAtMTA1ZS00YzU4LTkzOTYtNDhjY2FiMTJmM2IwIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3MzIyNzI0NDEsImNzcmYiOiIyZTM2NzVmOC00YmJjLTQ4ZDAtYjZmZS02OGQ2Nzk3YzFiZGMiLCJleHAiOjE3NjM4MDg0NDF9.cpDau60dfARdj4u9BNj_T9pe9cSWetPGpJk6gIouL7E"




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(!)jq5nqszl5iilmg4h6(5(cn@q_f0#w)=e)+_+n#0130j1bgx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.89.148.84', 'ipziyvfjadlv003.pwcglb.com']

SECURE_HSTS_SECONDS = 31536000
SECURE_CONTENT_TYPE_NOSNIFF = True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'invoiceapp',
    'sslserver',
    'rest_framework',
    'corsheaders'
    
]
# CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_ALL_ORIGINS = True

SESSION_SAVE_EVERY_REQUEST = True
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'invoiceapp.middleware.no_cache_middleware.NoCacheMiddleware', 
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'frontend/build')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
# APPEND_SLASH = False

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'db_idp',
        'USER':'SA',
        'PASSWORD':'Ocrdb@12#',
        'HOST':'127.0.0.1',
        'PORT':'',        
        'OPTIONS':  {
                    'driver':'ODBC Driver 17 for SQL Server',
                    'unicode_results': True,  
                    }
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SESSION_COOKIE_SECURE = False  
SESSION_COOKIE_SAMESITE = 'Lax' 
SESSION_COOKIE_HTTPONLY = True  
CSRF_COOKIE_NAME = "csrftoken"
SESSION_SAVE_EVERY_REQUEST = True


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend/build/static')
]
